name: Update wiki posts
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: "Update posts" 
    steps:
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/elysium-wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      - name: Update posts
        if: always()
        shell: bash
        run: |
          # Create the new_wiki directory if it doesn't exist
          mkdir -p ./wiki/new_wiki
      
          # Copy the .vitepress directory from the original "wiki" to "new_wiki"
          cp -R ./wiki/.vitepress ./wiki/new_wiki
      
          # Copy all files from "posts" to "new_wiki"
          cp -R ./posts/* ./wiki/new_wiki
      
          # Use rsync to synchronize the content from "new_wiki" into "wiki"
          rsync -a ./wiki/new_wiki/ ./wiki/
      
          cd wiki
      
          # Set Git user email and name
          git config --global user.email "elysium.mp@github.com"
          git config --global user.name "elysium.mp"
      
          # Commit all changes in "wiki"
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
      
          # Push the changes to the "main" branch of the current repository
          git push origin main || true
