name: Update wiki posts
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update posts
    steps:
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/elysium-wiki-website"
          path: "wiki2"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      - name: Create new_wiki directory
        run: |
          mkdir wiki2/new_wiki
        working-directory: wiki2

      - name: Move posts to new_wiki
        run: |
          mv ../posts/* new_wiki/
        working-directory: wiki2

      - name: Commit and push changes
        run: |
          git config user.email "elysium.mp@github.com"
          git config user.name "elysium.mp"
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
          git push || true
        working-directory: wiki2
